Contexts/Procurement/Veam.Purchase/Controllers/4. PO/API/PurchaseOrderLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using netcore.Data;
using netcore.Models.Invent;

namespace netcore.Controllers.Api
{

    [Produces("application/json")]
    [Route("api/PurchaseOrderLine")]
    public class PurchaseOrderLineController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PurchaseOrderLineController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/PurchaseOrderLine
        [HttpGet]
        [Authorize]
        public IActionResult GetPurchaseOrderLine(string masterid)
        {
            return Json(new { data = _context.PurchaseOrderLine.Include(x => x.product).Where(x => x.purchaseOrderId.Equals(masterid)).ToList() });
        }

        // POST: api/PurchaseOrderLine
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PostPurchaseOrderLine([FromBody] PurchaseOrderLine purchaseOrderLine)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            PurchaseOrder purchaseOrder = await _context.PurchaseOrder.Where(x => x.purchaseOrderId.Equals(purchaseOrderLine.purchaseOrderId)).FirstOrDefaultAsync();

            if (purchaseOrder.purchaseOrderStatus == PurchaseOrderStatus.Completed)
            {
                return Json(new { success = false, message = "Lỗi. Không thẻ sửa trạng thái [Completed]." });
            }

            purchaseOrderLine.totalAmount = (decimal)purchaseOrderLine.qty * purchaseOrderLine.price;

            if (purchaseOrderLine.purchaseOrderLineId == string.Empty)
            {
                purchaseOrderLine.purchaseOrderLineId = Guid.NewGuid().ToString();
                _context.PurchaseOrderLine.Add(purchaseOrderLine);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Add new data success." });
            }
            else
            {
                _context.Update(purchaseOrderLine);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Edit data success." });
            }

        }

        // DELETE: api/PurchaseOrderLine/5
        [HttpDelete("{id}")]
        [Authorize]
        public async Task<IActionResult>  DeletePurchaseOrderLine([FromRoute] string id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var purchaseOrderLine = await _context.PurchaseOrderLine
                .Include(x => x.purchaseOrder)
                .SingleOrDefaultAsync(m => m.purchaseOrderLineId == id);

            if (purchaseOrderLine == null)
            {
                return NotFound();
            }

            if (purchaseOrderLine.purchaseOrder.purchaseOrderStatus == PurchaseOrderStatus.Completed)
            {
                return Json(new { success = false, message = "Lỗi. Không thẻ xóa trạng thái [Completed]." });
            }

            _context.PurchaseOrderLine.Remove(purchaseOrderLine);
            await _context.SaveChangesAsync();

            return Json(new { success = true, message = "Delete success." });
        }


        private bool PurchaseOrderLineExists(string id)
        {
            return _context.PurchaseOrderLine.Any(e => e.purchaseOrderLineId == id);
        }


    }

}

Contexts/Procurement/Veam.Purchase/Controllers/4. PO/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;

using netcore.Data;
using netcore.Models.Invent;

namespace netcore.Controllers.Invent
{


    [Authorize(Roles = "PurchaseOrder")]
    public class PurchaseOrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PurchaseOrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ShowPurchaseOrder(string id)
        {
            PurchaseOrder obj = await _context.PurchaseOrder
                .Include(x => x.vendor)
                .Include(x => x.purchaseOrderLine).ThenInclude(x => x.product)
                .Include(x => x.branch)
                .SingleOrDefaultAsync(x => x.purchaseOrderId.Equals(id));

            obj.totalOrderAmount = obj.purchaseOrderLine.Sum(x => x.totalAmount);
            obj.totalDiscountAmount = obj.purchaseOrderLine.Sum(x => x.discountAmount);
            _context.Update(obj);

            return View(obj);
        }

        public async Task<IActionResult> PrintPurchaseOrder(string id)
        {
            PurchaseOrder obj = await _context.PurchaseOrder
                .Include(x => x.vendor)
                .Include(x => x.purchaseOrderLine).ThenInclude(x => x.product)
                .Include(x => x.branch)
                .SingleOrDefaultAsync(x => x.purchaseOrderId.Equals(id));
            return View(obj);
        }

        // GET: PurchaseOrder
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PurchaseOrder.OrderByDescending(x => x.createdAt).Include(p => p.vendor);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: PurchaseOrder/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseOrder = await _context.PurchaseOrder
                    .Include(x => x.purchaseOrderLine)
                    .Include(p => p.vendor)
                    .Include(x => x.branch)
                        .SingleOrDefaultAsync(m => m.purchaseOrderId == id);
            if (purchaseOrder == null)
            {
                return NotFound();
            }

            purchaseOrder.totalOrderAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.totalAmount);
            purchaseOrder.totalDiscountAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.discountAmount);
            _context.Update(purchaseOrder);
            await _context.SaveChangesAsync();

            return View(purchaseOrder);
        }


        // GET: PurchaseOrder/Create
        public IActionResult Create()
        {
            PurchaseOrder po = new PurchaseOrder();
            ViewData["vendorId"] = new SelectList(_context.Vendor, "vendorId", "vendorName");
            Branch defaultBranch = _context.Branch.Where(x => x.isDefaultBranch.Equals(true)).FirstOrDefault();
            ViewData["branchId"] = new SelectList(_context.Branch, "branchId", "branchName", defaultBranch != null ? defaultBranch.branchId : null);
            return View(po);
        }




        // POST: PurchaseOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("purchaseOrderId,purchaseOrderNumber,top,poDate,deliveryDate,deliveryAddress,referenceNumberInternal,referenceNumberExternal,description,vendorId,branchId,picInternal,picVendor,purchaseOrderStatus,totalDiscountAmount,totalOrderAmount,purchaseReceiveNumber,HasChild,createdAt")] PurchaseOrder purchaseOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(purchaseOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = purchaseOrder.purchaseOrderId });
            }
            ViewData["branchId"] = new SelectList(_context.Branch, "branchId", "branchName", purchaseOrder.branchId);
            ViewData["vendorId"] = new SelectList(_context.Vendor, "vendorId", "vendorName", purchaseOrder.vendorId);
            return View(purchaseOrder);
        }

        // GET: PurchaseOrder/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseOrder = await _context.PurchaseOrder.Include(x => x.purchaseOrderLine).SingleOrDefaultAsync(m => m.purchaseOrderId == id);
            if (purchaseOrder == null)
            {
                return NotFound();
            }

            purchaseOrder.totalOrderAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.totalAmount);
            purchaseOrder.totalDiscountAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.discountAmount);
            _context.Update(purchaseOrder);
            await _context.SaveChangesAsync();
            ViewData["branchId"] = new SelectList(_context.Branch, "branchId", "branchName", purchaseOrder.branchId);
            ViewData["vendorId"] = new SelectList(_context.Vendor, "vendorId", "vendorName", purchaseOrder.vendorId);
            TempData["PurchaseOrderStatus"] = purchaseOrder.purchaseOrderStatus;
            ViewData["StatusMessage"] = TempData["StatusMessage"];
            return View(purchaseOrder);
        }

        // POST: PurchaseOrder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("purchaseOrderId,purchaseOrderNumber,top,poDate,deliveryDate,deliveryAddress,referenceNumberInternal,referenceNumberExternal,description,vendorId,branchId,picInternal,picVendor,purchaseOrderStatus,totalDiscountAmount,totalOrderAmount,purchaseReceiveNumber,HasChild,createdAt")] PurchaseOrder purchaseOrder)
        {
            if (id != purchaseOrder.purchaseOrderId)
            {
                return NotFound();
            }
            

            if ((PurchaseOrderStatus)TempData["PurchaseOrderStatus"] == PurchaseOrderStatus.Completed)
            {
                TempData["StatusMessage"] = "Error. Cannot fix [Completed].";
                return RedirectToAction(nameof(Edit), new { id = purchaseOrder.purchaseOrderId });
            }

            if (purchaseOrder.purchaseOrderStatus == PurchaseOrderStatus.Completed)
            {
                TempData["StatusMessage"] = "Error. Unable to change Po Status [Completed].";
                return RedirectToAction(nameof(Edit), new { id = purchaseOrder.purchaseOrderId });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchaseOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchaseOrderExists(purchaseOrder.purchaseOrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["branchId"] = new SelectList(_context.Branch, "branchId", "branchName", purchaseOrder.branchId);
            ViewData["vendorId"] = new SelectList(_context.Vendor, "vendorId", "vendorName", purchaseOrder.vendorId);
            return View(purchaseOrder);
        }

        // GET: PurchaseOrder/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseOrder = await _context.PurchaseOrder
                    .Include(x => x.purchaseOrderLine)
                    .Include(p => p.vendor)
                    .SingleOrDefaultAsync(m => m.purchaseOrderId == id);
            if (purchaseOrder == null)
            {
                return NotFound();
            }

            purchaseOrder.totalOrderAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.totalAmount);
            purchaseOrder.totalDiscountAmount = purchaseOrder.purchaseOrderLine.Sum(x => x.discountAmount);
            _context.Update(purchaseOrder);
            await _context.SaveChangesAsync();

            return View(purchaseOrder);
        }




        // POST: PurchaseOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var purchaseOrder = await _context.PurchaseOrder
                .Include(x => x.purchaseOrderLine)
                .SingleOrDefaultAsync(m => m.purchaseOrderId == id);
            try
            {
                _context.PurchaseOrderLine.RemoveRange(purchaseOrder.purchaseOrderLine);
                _context.PurchaseOrder.Remove(purchaseOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewData["StatusMessage"] = "Error. Calm Down ^_^ and please contact your SysAdmin with this message: " + ex;
                return View(purchaseOrder);
            }
            
        }

Contexts/Procurement/Veam.Purchase/Views/PurchaseOrder/Delete.cshtml
@model netcore.Models.Invent.PurchaseOrder

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminlteNetcoreDelete.cshtml";
    ViewData["EntityIcon"] = "fa fa-file-text";
    ViewData["DeleteInfo"] = "[Completed] Cannot be delete (PO). Restore status to [Open] by deleting the relevant Products.";
    ViewData["IsCanDeleted"] = false;
    if (Model.purchaseOrderStatus != netcore.Models.Invent.PurchaseOrderStatus.Completed)
    {
        ViewData["IsCanDeleted"] = true;
    }
}


@Html.Partial("_StatusMessage", (string)ViewBag.StatusMessage)
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.purchaseOrderNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.purchaseOrderNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.top)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.top)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.poDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.poDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.deliveryDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.deliveryDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.deliveryAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.deliveryAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.referenceNumberInternal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.referenceNumberInternal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.referenceNumberExternal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.referenceNumberExternal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.branch)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.branch.branchName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.picInternal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.picInternal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.picVendor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.picVendor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.purchaseOrderStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.purchaseOrderStatus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.totalDiscountAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.totalDiscountAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.totalOrderAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.totalOrderAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.purchaseReceiveNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.purchaseReceiveNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.createdAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.createdAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.vendor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.vendor.vendorName)
        </dd>
    </dl>

</div>

Contexts/Procurement/Veam.Purchase/Views/PurchaseOrder/Details.cshtml
@model netcore.Models.Invent.PurchaseOrder

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminlteNetcoreDetails.cshtml";
    ViewData["EntityIcon"] = "fa fa-file-text";
}



<div class="row">
    <div class="col-md-9">
        <!-- Default box -->
        <div class="box box-primary">
            <div class="box-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.purchaseOrderNumber)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.purchaseOrderNumber)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.top)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.top)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.poDate)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.poDate)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.deliveryDate)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.deliveryDate)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.deliveryAddress)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.deliveryAddress)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.referenceNumberInternal)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.referenceNumberInternal)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.referenceNumberExternal)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.referenceNumberExternal)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.description)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.branch)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.branch.branchName)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.picInternal)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.picInternal)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.picVendor)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.picVendor)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.purchaseOrderStatus)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.purchaseOrderStatus)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.totalDiscountAmount)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.totalDiscountAmount)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.totalOrderAmount)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.totalOrderAmount)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.purchaseReceiveNumber)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.purchaseReceiveNumber)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.createdAt)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.createdAt)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.vendor)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.vendor.vendorName)
                        </dd>
                    </dl>                                   
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="form-group">
                    <a asp-action="Edit" asp-route-id="@Model.purchaseOrderId" class="btn btn-primary">Edit</a>
                    <a asp-action="ShowPurchaseOrder" asp-route-id="@Model.purchaseOrderId" class="btn btn-primary pull-right"><i class="fa fa-print"></i> Print PO</a>
                    <a asp-action="Index" class="btn btn-default">Return...</a>
                </div>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-md-3">
    </div>
</div>


<div class="row">
    <div class="col-md-9">
        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <table id="grid" name="grid" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th class="col-lg-3">Products</th>
                                    <th class="col-lg-3">Quantity</th>
                                    <th class="col-lg-3">Price</th>
                                    <th class="col-lg-1"></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12">
                            @if (Model.purchaseOrderStatus != netcore.Models.Invent.PurchaseOrderStatus.Completed)
                            {
                                <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("Create","PurchaseOrderLine", new { masterid = Model.purchaseOrderId })')"><i class="fa fa-plus"></i> Add Products</a>

                            }
                            
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-md-3">

    </div>
</div>



    <!--modal placeholder-->
    <div class="modal modal-primary fade" id="modalDefault">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
@section Scripts{
      <script>
        var popup, dataTable;
        var entity = 'PurchaseOrderLine';
        var apiurl = '/api/' + entity;

        $(document).ready(function () {
            dataTable = $('#grid').DataTable({
                "ajax": {
                    "url": apiurl + '?masterid=@Model.purchaseOrderId',
                    "type": 'GET',
                    "datatype": 'json'
                },
                "columns": [
                    { "data": "product.productCode" },
                    { "data": "qty" },
                    { "data": "price" },
                    {
                        "data": "purchaseOrderLineId",
                        "render": function (data) {
                            var btnEdit = "<a class='btn btn-primary btn-xs' onclick=ShowPopup('/" + entity + "/Create/" + data + "')><i class='fa fa-pencil'></i></a>";
                            var btnDelete = "<a class='btn btn-danger btn-xs' style='margin-left:2px' onclick=Delete('" + data + "')><i class='fa fa-trash'></i></a>";
                            return "<div class='tools pull-right'>" + btnEdit + btnDelete + "</div>";
                        }
                    }
                ],
                "language": {
                    "emptyTable": "no data found."
                },
                "lengthChange": false,
                "info": false,
                "searching": false,
                "paging": false,
            });
        });

        function ShowPopup(url) {
            var modalId = 'modalDefault';
            var modalPlaceholder = $('#' + modalId + ' .modal-dialog .modal-content');
            $.get(url)
                .done(function (response) {
                    modalPlaceholder.html(response);
                    popup = $('#' + modalId + '').modal({
                        keyboard: false,
                        backdrop: 'static'
                    });
                });
        }


        function SubmitAddEdit(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var data = $(form).serializeJSON();
                data = JSON.stringify(data);
                $.ajax({
                    type: 'POST',
                    url: apiurl,
                    data: data,
                    contentType: 'application/json',
                    success: function (data) {
                        if (data.success) {
                            popup.modal('hide');
                            ShowMessage(data.message);
                            dataTable.ajax.reload();
                        } else {
                            popup.modal('hide');
                            ShowMessageError(data.message);
                            dataTable.ajax.reload();
                        }
                    }
                });

            }
            return false;
        }

        function Delete(id) {
            swal({
                title: "Are you sure you want to delete?",
                text: "You will not be able to recover data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#dd4b39",
                confirmButtonText: "Agree, Delete!",
                closeOnConfirm: true
            }, function () {
                $.ajax({
                    type: 'DELETE',
                    url: apiurl + '/' + id,
                    success: function (data) {
                        if (data.success) {
                            ShowMessage(data.message);
                            dataTable.ajax.reload();
                        } else {
                            ShowMessageError(data.message);
                        }
                    }
                });
            });


        }

      </script>
}